### ISSUE TITLE
[Suggestion 2] Make running the app locally easier with docker

### ISSUE THREAD

**Issue by medbs** [javascriptteacher/primary#6]
Create docker-compose file for starting all the app related services (MYSQL for now) to avoid installing everything manually.

**Comment by ilyosjon09** [comment]
Can you make a PR for this functionality?

**Comment by medbs** [comment]
Yes I will.

**Comment by javascriptteacher** [comment]
Not sure if we need docker (or any other outside dependencies) for such a small API endpoint server. Time would be better spent actually adding new API end points, because that's where most of our progress is now. Check Trello as source of truth for all new issues, pick tasks from there, or let me know if you need me to add anything new (like add new API end point you can think of, that we don't have yet.)

**Comment by medbs** [comment]
Yes sure, but the idea is not about Dockerzing the app because it's too early for that. The idea is to start MySQL and import the dump without having to do it manually (I'm quite sure it can get tricky when it comes to managing the users access).
There's a Pull request for this, but we can put it on hold until making sure if it's really needed.

**Comment by javascriptteacher** [comment]
> Yes sure, but the idea is not about Dockerzing the app because it's too early for that. The idea is to start MySQL and import the dump without having to do it manually (I'm quite sure it can get tricky when it comes to managing the users access).
> There's a Pull request for this, but we can put it on hold until making sure if it's really needed.

Ok.
